eureka:
  client:
    serviceUrl:
      defaultZone: http://docker-compose-eureka:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 10021

spring:
  application:
    name: micro_sbdata



datasource:
  master:
    url: jdbc:sqlserver://47.103.13.21;DatabaseName=cloud_hotel
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: chenniao
  second:
    url: jdbc:mysql://172.16.4.236:3306/cloud_ida?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa112211!
    max-idle: 10
    max-wait: 10000
    min-idle: 1
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
