eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 10021

spring:
  datasource:
    url: jdbc:sqlserver://47.103.13.21;DatabaseName=CN_HMST_TEST
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: chenniao
  application:
    name: micro_sbdata

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.louhwz.sbdata.repository