eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 10021

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cn_fsthmst?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Aa112211!
  application:
    name: micro_sbdata

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.louhwz.sbdata.repository