eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 10011

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/cloud-ida?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      #driverClassName: com.mysql.jdbc.Driver
      username: root
      password: zsq1zsq12Mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: micro_register

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.louhwz.register.repository
